---
version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
      timezone: "Etc/UTC"
