---
name: Lint with StandardRB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4
      - name: StandardRB Linter
        uses: testdouble/standard-ruby-action@0.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
